"""Bandit system parameter inventory."""

from meta.schemas import MetaParameter


class BanditParameterInventorist:
    """Enumerates all meta-tunable parameters in the bandit subsystem."""

    def inventory(self) -> list:
        """Return list of MetaParameter for the bandit system."""
        return [
            MetaParameter(
                param_id="T_base",
                display_name="Base Temperature",
                system="bandit",
                type="float",
                default_value=0.025,
                valid_range={"min": 0.001, "max": 0.5},
                code_path="bandit/adaptive_bandit.py:AdaptiveBandit.compute_temperature",
                impact_hypothesis="Controls exploration-exploitation tradeoff; higher values increase exploration at the cost of convergence speed",
                sensitivity_estimate="high",
                category="temperature",
            ),
            MetaParameter(
                param_id="exploration_floor",
                display_name="Exploration Floor",
                system="bandit",
                type="float",
                default_value=0.05,
                valid_range={"min": 0.01, "max": 0.3},
                code_path="bandit/adaptive_bandit.py:AdaptiveBandit.select_arm",
                impact_hypothesis="Minimum exploration probability prevents premature convergence on suboptimal arms",
                sensitivity_estimate="medium",
                category="exploration",
            ),
            MetaParameter(
                param_id="paper_preference_ratio",
                display_name="Paper Preference Ratio",
                system="bandit",
                type="float",
                default_value=0.4,
                valid_range={"min": 0.0, "max": 1.0},
                code_path="bandit/adaptive_bandit.py:AdaptiveBandit.compute_arm_scores",
                impact_hypothesis="Balance between paper-inspired vs random mutations; higher values leverage literature more",
                sensitivity_estimate="medium",
                category="exploration",
            ),
            MetaParameter(
                param_id="K_reheat_threshold",
                display_name="Reheat Threshold (K)",
                system="bandit",
                type="int",
                default_value=5,
                valid_range={"min": 2, "max": 20},
                code_path="bandit/adaptive_bandit.py:AdaptiveBandit.check_reheat",
                impact_hypothesis="Number of consecutive non-improving iterations before temperature reheat; too low causes instability, too high delays recovery",
                sensitivity_estimate="medium",
                category="temperature",
            ),
            MetaParameter(
                param_id="reheat_factor",
                display_name="Reheat Factor",
                system="bandit",
                type="float",
                default_value=3.0,
                valid_range={"min": 1.0, "max": 10.0},
                code_path="bandit/adaptive_bandit.py:AdaptiveBandit.reheat",
                impact_hypothesis="Multiplier for temperature on reheat; larger values create stronger exploration bursts",
                sensitivity_estimate="medium",
                category="temperature",
            ),
            MetaParameter(
                param_id="min_temperature",
                display_name="Minimum Temperature",
                system="bandit",
                type="float",
                default_value=0.001,
                valid_range={"min": 0.0001, "max": 0.01},
                code_path="bandit/adaptive_bandit.py:AdaptiveBandit.compute_temperature",
                impact_hypothesis="Floor on temperature decay; prevents complete greedy lock-in",
                sensitivity_estimate="low",
                category="temperature",
            ),
            MetaParameter(
                param_id="enable_rollback_safety",
                display_name="Enable Rollback Safety",
                system="bandit",
                type="bool",
                default_value=True,
                valid_range={},
                code_path="bandit/adaptive_bandit.py:AdaptiveBandit.accept_or_reject",
                impact_hypothesis="When enabled, reverts config on degradation; disabling allows riskier exploration",
                sensitivity_estimate="high",
                category="exploration",
            ),
            # Boost rule weights
            MetaParameter(
                param_id="attention_entropy_arch_boost",
                display_name="Attention Entropy Architecture Boost",
                system="bandit",
                type="float",
                default_value=1.0,
                valid_range={"min": 0.0, "max": 5.0},
                code_path="bandit/boost_rules.py:BoostRules.attention_entropy_arch",
                impact_hypothesis="Weight for boosting arms that address attention entropy issues; higher values prioritize architectural fixes",
                sensitivity_estimate="low",
                category="prompt",
            ),
            MetaParameter(
                param_id="gradient_norm_lr_boost",
                display_name="Gradient Norm LR Boost",
                system="bandit",
                type="float",
                default_value=1.0,
                valid_range={"min": 0.0, "max": 5.0},
                code_path="bandit/boost_rules.py:BoostRules.gradient_norm_lr",
                impact_hypothesis="Weight for boosting arms targeting learning rate when gradient norms are abnormal",
                sensitivity_estimate="low",
                category="prompt",
            ),
            MetaParameter(
                param_id="loss_plateau_regularization_boost",
                display_name="Loss Plateau Regularization Boost",
                system="bandit",
                type="float",
                default_value=1.0,
                valid_range={"min": 0.0, "max": 5.0},
                code_path="bandit/boost_rules.py:BoostRules.loss_plateau_regularization",
                impact_hypothesis="Weight for boosting regularization-focused arms during loss plateaus",
                sensitivity_estimate="low",
                category="prompt",
            ),
            MetaParameter(
                param_id="param_utilization_pruning_boost",
                display_name="Parameter Utilization Pruning Boost",
                system="bandit",
                type="float",
                default_value=1.0,
                valid_range={"min": 0.0, "max": 5.0},
                code_path="bandit/boost_rules.py:BoostRules.param_utilization_pruning",
                impact_hypothesis="Weight for boosting pruning/efficiency arms when parameter utilization is low",
                sensitivity_estimate="low",
                category="prompt",
            ),
            MetaParameter(
                param_id="convergence_speed_schedule_boost",
                display_name="Convergence Speed Schedule Boost",
                system="bandit",
                type="float",
                default_value=1.0,
                valid_range={"min": 0.0, "max": 5.0},
                code_path="bandit/boost_rules.py:BoostRules.convergence_speed_schedule",
                impact_hypothesis="Weight for boosting schedule-related arms based on convergence speed diagnostics",
                sensitivity_estimate="low",
                category="prompt",
            ),
            MetaParameter(
                param_id="weight_norm_init_boost",
                display_name="Weight Norm Initialization Boost",
                system="bandit",
                type="float",
                default_value=1.0,
                valid_range={"min": 0.0, "max": 5.0},
                code_path="bandit/boost_rules.py:BoostRules.weight_norm_init",
                impact_hypothesis="Weight for boosting initialization-focused arms when weight norms diverge",
                sensitivity_estimate="low",
                category="prompt",
            ),
            MetaParameter(
                param_id="token_diversity_embedding_boost",
                display_name="Token Diversity Embedding Boost",
                system="bandit",
                type="float",
                default_value=1.0,
                valid_range={"min": 0.0, "max": 5.0},
                code_path="bandit/boost_rules.py:BoostRules.token_diversity_embedding",
                impact_hypothesis="Weight for boosting embedding-focused arms when token diversity metrics are poor",
                sensitivity_estimate="low",
                category="prompt",
            ),
            MetaParameter(
                param_id="activation_sparsity_width_boost",
                display_name="Activation Sparsity Width Boost",
                system="bandit",
                type="float",
                default_value=1.0,
                valid_range={"min": 0.0, "max": 5.0},
                code_path="bandit/boost_rules.py:BoostRules.activation_sparsity_width",
                impact_hypothesis="Weight for boosting width-related arms when activation sparsity is high",
                sensitivity_estimate="low",
                category="prompt",
            ),
        ]
