"""GPU Kernel system parameter inventory."""

from meta.schemas import MetaParameter


class GPUKernelParameterInventorist:
    """Enumerates all meta-tunable parameters in the GPU kernel subsystem."""

    def inventory(self) -> list:
        """Return list of MetaParameter for the GPU kernel system."""
        return [
            MetaParameter(
                param_id="kernel_benchmark_n_warmup",
                display_name="Kernel Benchmark Warmup Iterations",
                system="gpu_kernels",
                type="int",
                default_value=10,
                valid_range={"min": 1, "max": 50},
                code_path="gpu_kernels/benchmark.py:KernelBenchmark.warmup",
                impact_hypothesis="Number of warmup iterations before timing; more warmup reduces variance but increases benchmarking time",
                sensitivity_estimate="low",
                category="evaluation",
            ),
            MetaParameter(
                param_id="kernel_benchmark_n_timed",
                display_name="Kernel Benchmark Timed Iterations",
                system="gpu_kernels",
                type="int",
                default_value=100,
                valid_range={"min": 10, "max": 500},
                code_path="gpu_kernels/benchmark.py:KernelBenchmark.time",
                impact_hypothesis="Number of timed iterations for benchmarking; more iterations give more precise measurements",
                sensitivity_estimate="low",
                category="evaluation",
            ),
            MetaParameter(
                param_id="kernel_benchmark_n_runs",
                display_name="Kernel Benchmark Number of Runs",
                system="gpu_kernels",
                type="int",
                default_value=3,
                valid_range={"min": 1, "max": 10},
                code_path="gpu_kernels/benchmark.py:KernelBenchmark.run_all",
                impact_hypothesis="Number of independent benchmark runs for statistical robustness",
                sensitivity_estimate="low",
                category="evaluation",
            ),
            MetaParameter(
                param_id="kernel_evolution_max_generations",
                display_name="Kernel Evolution Max Generations",
                system="gpu_kernels",
                type="int",
                default_value=20,
                valid_range={"min": 5, "max": 100},
                code_path="gpu_kernels/evolution.py:KernelEvolution.evolve",
                impact_hypothesis="Maximum generations for evolutionary kernel search; more generations allow deeper optimization",
                sensitivity_estimate="medium",
                category="budget",
            ),
            MetaParameter(
                param_id="kernel_evolution_min_improvement",
                display_name="Kernel Evolution Minimum Improvement",
                system="gpu_kernels",
                type="float",
                default_value=0.01,
                valid_range={"min": 0.001, "max": 0.1},
                code_path="gpu_kernels/evolution.py:KernelEvolution.should_stop",
                impact_hypothesis="Minimum relative improvement to continue evolution; lower values search longer for marginal gains",
                sensitivity_estimate="medium",
                category="evaluation",
            ),
            MetaParameter(
                param_id="kernel_refinement_cooldown",
                display_name="Kernel Refinement Cooldown",
                system="gpu_kernels",
                type="int",
                default_value=5,
                valid_range={"min": 1, "max": 20},
                code_path="gpu_kernels/evolution.py:KernelEvolution.cooldown",
                impact_hypothesis="Iterations to wait between kernel refinement attempts; prevents thrashing on marginal improvements",
                sensitivity_estimate="low",
                category="scheduling",
            ),
            MetaParameter(
                param_id="kernel_runtime_check_interval",
                display_name="Kernel Runtime Check Interval",
                system="gpu_kernels",
                type="int",
                default_value=10,
                valid_range={"min": 1, "max": 50},
                code_path="gpu_kernels/monitor.py:KernelMonitor.check_runtime",
                impact_hypothesis="How often kernel runtime is re-checked during training; more frequent checks detect regressions faster",
                sensitivity_estimate="low",
                category="scheduling",
            ),
            MetaParameter(
                param_id="kernel_mutations_per_generation",
                display_name="Kernel Mutations Per Generation",
                system="gpu_kernels",
                type="int",
                default_value=5,
                valid_range={"min": 1, "max": 20},
                code_path="gpu_kernels/evolution.py:KernelEvolution.mutate",
                impact_hypothesis="Number of mutation variants generated per evolution generation; more mutations increase diversity but cost more compute",
                sensitivity_estimate="medium",
                category="exploration",
            ),
            MetaParameter(
                param_id="kernel_discovery_block_sizes",
                display_name="Kernel Discovery Block Sizes",
                system="gpu_kernels",
                type="str",
                default_value="64,128,256",
                valid_range={"enum": ["32,64,128", "64,128,256", "128,256,512", "64,128,256,512"]},
                code_path="gpu_kernels/discovery.py:KernelDiscovery.search_block_sizes",
                impact_hypothesis="Block size configurations to explore; wider search finds better configurations but takes longer",
                sensitivity_estimate="medium",
                category="exploration",
            ),
        ]
