"""Model Scientist system parameter inventory."""

from meta.schemas import MetaParameter


class ModelScientistParameterInventorist:
    """Enumerates all meta-tunable parameters in the model scientist subsystem."""

    def inventory(self) -> list:
        """Return list of MetaParameter for the model scientist system."""
        return [
            MetaParameter(
                param_id="scale_gate_enabled",
                display_name="Scale Gate Enabled",
                system="model_scientist",
                type="bool",
                default_value=True,
                valid_range={},
                code_path="model_scientist/pipeline.py:ModelScientist.run_training",
                impact_hypothesis="Enables scale-aware gating; disabling may simplify architecture search at cost of training stability",
                sensitivity_estimate="high",
                category="evaluation",
            ),
            MetaParameter(
                param_id="ablation_enabled",
                display_name="Ablation Enabled",
                system="model_scientist",
                type="bool",
                default_value=True,
                valid_range={},
                code_path="model_scientist/pipeline.py:ModelScientist.run_ablation",
                impact_hypothesis="Enables ablation studies; disabling saves compute but reduces understanding of component contributions",
                sensitivity_estimate="medium",
                category="evaluation",
            ),
            MetaParameter(
                param_id="min_training_steps",
                display_name="Minimum Training Steps",
                system="model_scientist",
                type="int",
                default_value=500,
                valid_range={"min": 100, "max": 5000},
                code_path="model_scientist/pipeline.py:ModelScientist.run_training",
                impact_hypothesis="Minimum steps before evaluation; too few produces noisy signals, too many wastes compute on bad architectures",
                sensitivity_estimate="high",
                category="evaluation",
            ),
            MetaParameter(
                param_id="max_training_steps",
                display_name="Maximum Training Steps",
                system="model_scientist",
                type="int",
                default_value=2000,
                valid_range={"min": 500, "max": 10000},
                code_path="model_scientist/pipeline.py:ModelScientist.run_training",
                impact_hypothesis="Maximum training budget per candidate; controls compute-quality tradeoff",
                sensitivity_estimate="high",
                category="budget",
            ),
            MetaParameter(
                param_id="n_eval_seeds",
                display_name="Number of Evaluation Seeds",
                system="model_scientist",
                type="int",
                default_value=1,
                valid_range={"min": 1, "max": 5},
                code_path="model_scientist/pipeline.py:ModelScientist.evaluate",
                impact_hypothesis="More seeds reduce evaluation variance but multiply compute cost linearly",
                sensitivity_estimate="medium",
                category="evaluation",
            ),
            MetaParameter(
                param_id="diagnostics_capture_interval",
                display_name="Diagnostics Capture Interval",
                system="model_scientist",
                type="int",
                default_value=50,
                valid_range={"min": 10, "max": 500},
                code_path="model_scientist/diagnostics.py:DiagnosticsCapture.capture",
                impact_hypothesis="How often training diagnostics are captured; more frequent provides richer signals for the bandit but adds overhead",
                sensitivity_estimate="low",
                category="scheduling",
            ),
            MetaParameter(
                param_id="failure_mining_interval",
                display_name="Failure Mining Interval",
                system="model_scientist",
                type="int",
                default_value=10,
                valid_range={"min": 1, "max": 50},
                code_path="model_scientist/failure_mining.py:FailureMiner.mine",
                impact_hypothesis="Iterations between failure pattern mining; more frequent mining discovers failure modes faster",
                sensitivity_estimate="low",
                category="scheduling",
            ),
            MetaParameter(
                param_id="metric_correlation_threshold",
                display_name="Metric Correlation Threshold",
                system="model_scientist",
                type="float",
                default_value=0.7,
                valid_range={"min": 0.3, "max": 0.95},
                code_path="model_scientist/diagnostics.py:DiagnosticsCapture.correlate_metrics",
                impact_hypothesis="Threshold for considering metrics correlated; affects which diagnostics influence arm selection",
                sensitivity_estimate="medium",
                category="evaluation",
            ),
            MetaParameter(
                param_id="max_active_metrics",
                display_name="Maximum Active Metrics",
                system="model_scientist",
                type="int",
                default_value=20,
                valid_range={"min": 5, "max": 50},
                code_path="model_scientist/diagnostics.py:DiagnosticsCapture.select_metrics",
                impact_hypothesis="Caps the number of tracked metrics to prevent context window bloat",
                sensitivity_estimate="low",
                category="budget",
            ),
            MetaParameter(
                param_id="critic_proposal_frequency",
                display_name="Critic Proposal Frequency",
                system="model_scientist",
                type="int",
                default_value=5,
                valid_range={"min": 1, "max": 20},
                code_path="model_scientist/pipeline.py:ModelScientist.generate_proposals",
                impact_hypothesis="How often the critic generates new architecture proposals; affects innovation vs exploitation balance",
                sensitivity_estimate="medium",
                category="scheduling",
            ),
        ]
