"""Surrogate Triage system parameter inventory."""

from meta.schemas import MetaParameter


class SurrogateTriageParameterInventorist:
    """Enumerates all meta-tunable parameters in the surrogate triage subsystem."""

    def inventory(self) -> list:
        """Return list of MetaParameter for the surrogate triage system."""
        return [
            MetaParameter(
                param_id="surrogate_retrain_threshold",
                display_name="Surrogate Retrain Threshold",
                system="surrogate_triage",
                type="float",
                default_value=0.1,
                valid_range={"min": 0.01, "max": 0.5},
                code_path="surrogate_triage/surrogate.py:Surrogate.should_retrain",
                impact_hypothesis="Prediction error threshold triggering surrogate retraining; lower values keep surrogate accurate but retrain more often",
                sensitivity_estimate="high",
                category="evaluation",
            ),
            MetaParameter(
                param_id="surrogate_training_epochs",
                display_name="Surrogate Training Epochs",
                system="surrogate_triage",
                type="int",
                default_value=100,
                valid_range={"min": 10, "max": 500},
                code_path="surrogate_triage/surrogate.py:Surrogate.train",
                impact_hypothesis="Training epochs per surrogate fit; more epochs improve accuracy but increase overhead",
                sensitivity_estimate="medium",
                category="budget",
            ),
            MetaParameter(
                param_id="surrogate_learning_rate",
                display_name="Surrogate Learning Rate",
                system="surrogate_triage",
                type="float",
                default_value=0.001,
                valid_range={"min": 0.0001, "max": 0.01},
                code_path="surrogate_triage/surrogate.py:Surrogate.train",
                impact_hypothesis="Learning rate for surrogate model training; affects convergence speed and final accuracy",
                sensitivity_estimate="medium",
                category="evaluation",
            ),
            MetaParameter(
                param_id="surrogate_k_folds",
                display_name="Surrogate K-Folds",
                system="surrogate_triage",
                type="int",
                default_value=5,
                valid_range={"min": 2, "max": 10},
                code_path="surrogate_triage/surrogate.py:Surrogate.cross_validate",
                impact_hypothesis="Number of cross-validation folds for surrogate evaluation; more folds give better estimates at higher cost",
                sensitivity_estimate="low",
                category="evaluation",
            ),
            MetaParameter(
                param_id="cold_start_conservative_threshold",
                display_name="Cold Start Conservative Threshold",
                system="surrogate_triage",
                type="int",
                default_value=10,
                valid_range={"min": 3, "max": 30},
                code_path="surrogate_triage/triage.py:Triage.cold_start_policy",
                impact_hypothesis="Number of observations before surrogate predictions are trusted at all; too low risks bad early filtering",
                sensitivity_estimate="high",
                category="exploration",
            ),
            MetaParameter(
                param_id="cold_start_full_threshold",
                display_name="Cold Start Full Trust Threshold",
                system="surrogate_triage",
                type="int",
                default_value=30,
                valid_range={"min": 10, "max": 100},
                code_path="surrogate_triage/triage.py:Triage.cold_start_policy",
                impact_hypothesis="Number of observations before surrogate is fully trusted for filtering; controls transition from exploration to exploitation",
                sensitivity_estimate="medium",
                category="exploration",
            ),
            MetaParameter(
                param_id="max_queue_size",
                display_name="Maximum Queue Size",
                system="surrogate_triage",
                type="int",
                default_value=100,
                valid_range={"min": 20, "max": 500},
                code_path="surrogate_triage/triage.py:Triage.manage_queue",
                impact_hypothesis="Maximum candidates in the triage queue; larger queues allow more diversity but increase processing time",
                sensitivity_estimate="low",
                category="budget",
            ),
            MetaParameter(
                param_id="dedup_threshold",
                display_name="Deduplication Threshold",
                system="surrogate_triage",
                type="float",
                default_value=0.95,
                valid_range={"min": 0.8, "max": 0.99},
                code_path="surrogate_triage/triage.py:Triage.deduplicate",
                impact_hypothesis="Cosine similarity threshold for deduplicating candidates; lower values filter more aggressively",
                sensitivity_estimate="low",
                category="exploration",
            ),
            MetaParameter(
                param_id="paper_filter_threshold",
                display_name="Paper Filter Threshold",
                system="surrogate_triage",
                type="float",
                default_value=0.3,
                valid_range={"min": 0.1, "max": 0.8},
                code_path="surrogate_triage/ingestion.py:PaperIngestion.filter",
                impact_hypothesis="Minimum relevance score for papers to enter the pipeline; lower values increase diversity but add noise",
                sensitivity_estimate="medium",
                category="exploration",
            ),
            MetaParameter(
                param_id="daily_ingestion_max_results",
                display_name="Daily Ingestion Max Results",
                system="surrogate_triage",
                type="int",
                default_value=50,
                valid_range={"min": 10, "max": 200},
                code_path="surrogate_triage/ingestion.py:PaperIngestion.fetch_daily",
                impact_hypothesis="Maximum papers ingested per day; controls information flow rate into the pipeline",
                sensitivity_estimate="low",
                category="budget",
            ),
            MetaParameter(
                param_id="ceiling_monitor_window_size",
                display_name="Ceiling Monitor Window Size",
                system="surrogate_triage",
                type="int",
                default_value=20,
                valid_range={"min": 5, "max": 50},
                code_path="surrogate_triage/ceiling.py:CeilingMonitor.check",
                impact_hypothesis="Window size for detecting performance ceilings; larger windows reduce false positives but delay detection",
                sensitivity_estimate="medium",
                category="evaluation",
            ),
        ]
